version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../public:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql
  redis:
    container_name: redis
    image: redis
  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../public:/var/www
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql:mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: qwerty
      PMA_HOST: mysql
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
    command: --default-authentication-plugin=mysql_native_password