version: '3.2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/core/nginx.conf:/etc/nginx/nginx.conf     
      - ../:/var/www
 
      - ./nginx/Logs:/var/core/Logs
    depends_on:
      - php
      - mysql
  mysql:
    container_name: mysql
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zumba3030+
  redis:
    container_name: redis
    image: redis
  php:
    container_name: php
    build:
      context: .
      dockerfile: php-frm/Dockerfile
    ports:
        - '9000:9000'

    volumes:
            - ../:/var/www
    environment:
            XDEBUG: "true" # optional: "false" by default        

    links:
            - mysql:mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: zumba3030+
      PMA_HOST: mysql   
    links:
             - mysql:mysql
    restart: always  
 